[package]
name = "safe-frost"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
publish = false

[dependencies]
anyhow = "1"
argh = "0.1"
frost = { package = "frost-secp256k1", version = "2", features = ["serialization"] }
k256 = "0.13"
postcard = "1"
rand = "0.8"
sha3 = "0.10"
