[package]
name = "safe-frost"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
publish = false

[dependencies]
argh = "0.1"
frost = { package = "frost-secp256k1", version = "2" }
k256 = "0.13"
rand = "0.8"
sha3 = "0.10"
