[profile.default]
src = "contracts"
libs = ["lib"]
test = "tests"
out = "target/foundry"
cache_path = "target/foundry/cache"

solc_version = "0.8.29"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true
